# Generated by Django 3.1 on 2020-08-17 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Personal statement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal statement',
                'verbose_name_plural': 'Personal statements',
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HARD', 'Hard skills'), ('SOFT', 'Soft skills')], default='SOFT', max_length=50, verbose_name='Type')),
                ('level', models.CharField(choices=[('B', 'Beginner'), ('S', 'Skilled'), ('A', 'Advanced'), ('E', 'Expert')], default='S', max_length=50, verbose_name='Level')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('F', 'Male'), ('M', 'Female')], default='F', max_length=10, verbose_name='Gender')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=300, null=True, verbose_name='Website')),
                ('linkedin', models.URLField(blank=True, verbose_name='Linkedin')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='LetterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Motivation letter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motivation letter',
                'verbose_name_plural': 'Motivation letters',
            },
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BAS', 'Basic'), ('ADV', 'Advanced'), ('PRO', 'Professional'), ('BIL', 'Bilingual')], default='BAS', max_length=50, verbose_name='Level')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='InterestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('None', 'Unknown'), ('SALAR', 'Salaried'), ('CHIEF', 'Founder/chief'), ('FREEL', 'Freelance/chief'), ('INTER', 'Internship'), ('OTHER', 'other')], default='INTER', max_length=10, verbose_name='Type')),
                ('position', models.CharField(max_length=200, verbose_name='Position')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('context', models.TextField(blank=True, max_length=1000, verbose_name='Context')),
                ('summary', models.TextField(blank=True, max_length=3000, verbose_name='Summary')),
                ('start_date', models.DateField(blank=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, verbose_name='End Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('institution', models.CharField(max_length=150, verbose_name='Institution')),
                ('level', models.CharField(choices=[('PE', 'Primary education'), ('LSE', 'Lower secondary education'), ('USE', 'Upper secondary education'), ('PS', 'Postsecondary non - tertiary education'), ('SCT', 'Short - cycle tertiary education'), ('BL', 'Bachelor’s or equivalent level'), ('ML', 'Master’s or equivalent level'), ('DL', 'Doctor or equivalent level')], default='USE', max_length=50, verbose_name='Level')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, verbose_name='End Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('institution', models.CharField(max_length=150, verbose_name='Institution')),
                ('level', models.CharField(choices=[('PE', 'Primary education'), ('LSE', 'Lower secondary education'), ('USE', 'Upper secondary education'), ('PS', 'Postsecondary non - tertiary education'), ('SCT', 'Short - cycle tertiary education'), ('BL', 'Bachelor’s or equivalent level'), ('ML', 'Master’s or equivalent level'), ('DL', 'Doctor or equivalent level')], default='USE', max_length=50, verbose_name='Level')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, verbose_name='End Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('authority', models.CharField(max_length=125, verbose_name='Authority')),
                ('description', models.TextField(blank=True, max_length=125, verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date obtained')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-date'],
            },
        ),
    ]
